#!/bin/bash
find . -type f name "*.gif" | rev | cut -d "/" -f 1 | rev | cut -d "." -f 2- | rev | LC_ALL=C sort -f

Footer

© 2022 GitHub, Inc.

Footer navigation

Terms

Privacy

Security

Status

Docs

Contact GitHub

Pricing


